name: frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  go_router: ^16.0.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/buyer.png
    - assets/icons/chicken.png
    - assets/icons/farmer.png
    - assets/icons/gardening.png
    - assets/icons/handicrafts.png
    - assets/icons/juicer.png
    - assets/icons/meat.png
    - assets/icons/seller.png
    - assets/images/logo_dark.png
    - assets/images/logo_light.png
    - assets/images/women_hands.jpeg
    - assets/images/farmer.jpeg
    - assets/images/customer.jpeg
    - assets/images/creator.jpeg
