name: frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  go_router: ^16.0.0
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/buyer.png
    - assets/icons/seller.png
    - assets/icons/map.png
    - assets/icons/home.png
    - assets/icons/tender.png
    - assets/icons/heart.png
    - assets/icons/user.png
    - assets/icons/add.png
    - assets/images/logo_dark.png
    - assets/images/logo_light.png
    - assets/images/women_hands.jpeg
    - assets/images/farmer.jpeg
    - assets/images/customer.jpeg
    - assets/images/creator.jpeg
